"""Add task priority and worker fields

Revision ID: 11b23c79bda3
Revises: 1dfb35f57dca
Create Date: 2026-04-19 03:04:43.706402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11b23c79bda3'
down_revision: Union[str, Sequence[str], None] = '1dfb35f57dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='taskpriority', native_enum=False), nullable=False))
    op.add_column('task', sa.Column('gpu_budget', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('retries', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('task', 'model',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('task', 'status',
               existing_type=postgresql.ENUM('QUEUED', 'SCORING', 'PROCESSING', 'COMPLETED', 'FAILED', name='task_status'),
               type_=sa.Enum('QUEUED', 'SCORING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('user_account', 'email',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user_account', 'password_hash',
               existing_type=sa.VARCHAR(length=72),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=72),
               existing_nullable=False)
    op.alter_column('user_account', 'email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('task', 'status',
               existing_type=sa.Enum('QUEUED', 'SCORING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus', native_enum=False),
               type_=postgresql.ENUM('QUEUED', 'SCORING', 'PROCESSING', 'COMPLETED', 'FAILED', name='task_status'),
               existing_nullable=False)
    op.alter_column('task', 'model',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('task', 'completed_at')
    op.drop_column('task', 'started_at')
    op.drop_column('task', 'retries')
    op.drop_column('task', 'gpu_budget')
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
