"""add task and user table

Revision ID: 1dfb35f57dca
Revises: 4a3c3710cf58
Create Date: 2026-04-18 14:53:52.177902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dfb35f57dca'
down_revision: Union[str, Sequence[str], None] = '4a3c3710cf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('password_hash', sa.String(length=72), nullable=False))
    op.add_column('user_account', sa.Column('refresh_token', sa.String(), nullable=True))
    op.drop_column('user_account', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('password', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_column('user_account', 'refresh_token')
    op.drop_column('user_account', 'password_hash')
    # ### end Alembic commands ###
