"""add_ai_fields

Revision ID: 6a8f70bcde81
Revises: 83581687fa19
Create Date: 2026-04-20 01:32:26.974268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8f70bcde81'
down_revision: Union[str, Sequence[str], None] = '83581687fa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('input_text', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('output_text', sa.Text(), nullable=True))
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('task', 'model',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('user_account', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    op.add_column('user_account', sa.Column('anthropic_api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'anthropic_api_key')
    op.drop_column('user_account', 'openai_api_key')
    op.alter_column('task', 'model',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('task', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('task', 'output_text')
    op.drop_column('task', 'input_text')
    # ### end Alembic commands ###
