"""add jobs and attachments

Revision ID: c092691f839f
Revises: ee7bf0b63d9a
Create Date: 2026-04-20 03:37:50.990655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c092691f839f'
down_revision: Union[str, Sequence[str], None] = 'ee7bf0b63d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SCORING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('capacity_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('LINK', 'FILE', 'PHOTO', name='attachmenttype', native_enum=False), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_task_id'), 'attachment', ['task_id'], unique=False)
    op.add_column('task', sa.Column('job_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_task_job_id'), 'task', ['job_id'], unique=False)
    op.create_foreign_key(None, 'task', 'job', ['job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_job_id'), table_name='task')
    op.drop_column('task', 'job_id')
    op.drop_index(op.f('ix_attachment_task_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
