"""add_gemini_key

Revision ID: ee7bf0b63d9a
Revises: 6a8f70bcde81
Create Date: 2026-04-20 01:57:33.655715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7bf0b63d9a'
down_revision: Union[str, Sequence[str], None] = '6a8f70bcde81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('gemini_api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'gemini_api_key')
    # ### end Alembic commands ###
